storage = [
	{"id": 531,
	 "title": "Interia",
	 "description": "Strona dziennikarska",
	 "source": "www.interia.pl",
	 "tags": ["info"],
	 "link": "https://www.interia.pl",
	 "createdDate": "1555234406"},

	{"id": 532,
	 "title": "Sport",
	 "description": "Strona dziennikarska",
	 "source": "www.sport.pl",
	 "tags": ["info", "sport"],
	 "link": "https://www.sport.pl",
	 "createdDate": "1555234406"},

	{"id": 533,
	 "title": "Facebook",
	 "description": "Portal spolecznosciowy",
	 "source": "www.facebook.com",
	 "tags": ["fun"],
	 "link": "https://www.facebook.com",
	 "createdDate": "1555234406"},
]
